use_frameworks!

platform :ios, '8.0'


target 'DNVideoPlayer_Example' do
#  inhibit_warnings 忽略警告
    pod 'DNVideoPlayer', :path => '../'
    pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK', :inhibit_warnings => true
    pod 'Masonry', :inhibit_warnings => true

  target 'DNVideoPlayer_Tests' do
    inherit! :search_paths

    
  end
end
