use_frameworks!

platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/DoNewsCode/DNSpecs.git'


target 'DNVideoPlayer_Example' do
#  inhibit_warnings 忽略警告
    pod 'DNVideoPlayer', :path => '../'
    pod 'AliyunPlayer_iOS/AliyunVodPlayerSDK','3.4.8' 
    pod 'Masonry', :inhibit_warnings => true
    pod 'DNCommonKit'

  target 'DNVideoPlayer_Tests' do
    inherit! :search_paths


    
  end
end
